# Generated by Django 6.0.2 on 2026-03-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('rating', models.FloatField(default=4.5)),
                ('work_type', models.CharField(choices=[('local', 'Local Service Worker'), ('freelancer', 'Freelancer'), ('company', 'Company')], max_length=20)),
                ('mode', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('both', 'Both')], max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(upload_to='providers/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
