# Generated by Django 6.0.2 on 2026-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_serviceprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('home', 'Home & Local Services'), ('professional', 'Professional & Freelance Services'), ('skilled', 'Local Skilled Workers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=10),
        ),
    ]
