# Generated by Django 6.0.2 on 2026-03-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_address_user_city_user_first_name_user_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
