# Generated by Django 6.0.2 on 2026-03-20 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount',
            new_name='company_margin',
        ),
        migrations.AddField(
            model_name='booking',
            name='estimate_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='providers/'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_time', models.CharField(choices=[('09:00', '9–10 AM'), ('10:00', '10–11 AM'), ('11:00', '11 AM–12 PM'), ('12:00', '12–1 PM'), ('13:00', '1–2 PM'), ('14:00', '2–3 PM'), ('15:00', '3–4 PM'), ('16:00', '4–5 PM'), ('17:00', '5–6 PM')], max_length=10)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.serviceprovider')),
            ],
            options={
                'ordering': ['date', 'slot_time'],
                'unique_together': {('provider', 'date', 'slot_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.timeslot'),
        ),
    ]
