# Generated by Django 6.0.2 on 2026-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimate_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimate_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimate_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
